/* Paper XII receipt w2 -- exhaustive orbit enumeration of orientations sigma in {+-1}^(N-1) on
 * F_2^n under the D-invariance group  <translations> x <GL(n,2)>.
 *
 * Encoding: orientation = (N-1)-bit integer; bit (a-1) set  <=>  sigma_a = +1.
 *
 * Generators:
 *   - translations by e_i (i<n): sigma_a ^= (chi_a(e_i) == -1), i.e.
 *     XOR with mask_i = { bits (a-1) : a has bit i set }.
 *   - GL(n,2) acting on masks a (covector action): generated by
 *       cyc:  bit i -> bit (i+1 mod n)
 *       swap: bits 0,1 exchanged
 *       tv:   bit1 ^= bit0        (transvection)
 *     (coordinate permutations + one transvection generate GL(n,2)).
 *
 * BFS over all 2^(N-1) states with a visited bitmap gives the COMPLETE
 * orbit partition by construction; completeness certificate = orbit sizes
 * sum to 2^(N-1).
 *
 * Output: one line per orbit: canonical (= minimal) representative, size.
 * Usage: ./orbit_bfs n   (n = 2..5)
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

static int n, N, M;              /* M = N-1 bits per state */
static uint32_t nstates_hi;      /* number of states = 2^M (fits u64) */

static uint32_t apply_mask_perm(uint32_t st, const uint8_t *perm)
{
    /* new state: bit perm[a]-1 of out = bit a-1 of st, masks 1..M */
    uint32_t out = 0;
    for (int a = 1; a <= M; a++)
        if (st & (1u << (a - 1)))
            out |= 1u << (perm[a] - 1);
    return out;
}

int main(int argc, char **argv)
{
    n = (argc > 1) ? atoi(argv[1]) : 5;
    N = 1 << n;  M = N - 1;
    uint64_t total = 1ull << M;

    /* translation XOR masks */
    uint32_t tmask[8];
    for (int i = 0; i < n; i++) {
        tmask[i] = 0;
        for (int a = 1; a <= M; a++)
            if (a & (1 << i)) tmask[i] |= 1u << (a - 1);
    }

    /* GL generators as mask permutations (on 1..M), plus inverses for safety */
    uint8_t cyc[64], swp[64], tv[64], cyci[64], tvi[64];
    for (int a = 1; a <= M; a++) {
        /* cyc: rotate bits up */
        uint32_t b = 0;
        for (int i = 0; i < n; i++) if (a & (1 << i)) b |= 1u << ((i + 1) % n);
        cyc[a] = (uint8_t)b;
        /* cyc inverse: rotate down */
        b = 0;
        for (int i = 0; i < n; i++) if (a & (1 << i)) b |= 1u << ((i + n - 1) % n);
        cyci[a] = (uint8_t)b;
        /* swap bits 0,1 */
        b = a & ~3u;
        if (a & 1) b |= 2;
        if (a & 2) b |= 1;
        swp[a] = (uint8_t)b;
        /* transvection: bit1 ^= bit0 */
        b = a;
        if (a & 1) b ^= 2;
        tv[a] = (uint8_t)b;
        tvi[a] = (uint8_t)b;   /* involution */
    }

    /* precomputed byte tables for the three distinct perms (speed) */
    /* generic path is fast enough for n<=5: 2^31 * 8 gens * ~40ns ~ 11 min; accept */

    uint8_t *visited = calloc(total / 8 + 1, 1);
    if (!visited) { fprintf(stderr, "no mem\n"); return 1; }
    uint32_t *stack = malloc(sizeof(uint32_t) * (1ull << (M > 28 ? 28 : M)));
    uint64_t stack_cap = (1ull << (M > 28 ? 28 : M));
    if (!stack) { fprintf(stderr, "no mem2\n"); return 1; }

    char fname[64];
    snprintf(fname, sizeof fname, "orbits_n%d.txt", n);
    FILE *out = fopen(fname, "w");
    uint64_t norbits = 0, checksum = 0;

    for (uint64_t start = 0; start < total; start++) {
        if (visited[start >> 3] & (1u << (start & 7))) continue;
        /* BFS/DFS this orbit */
        uint64_t size = 0;
        uint32_t rep = (uint32_t)start;
        uint64_t sp = 0;
        stack[sp++] = (uint32_t)start;
        visited[start >> 3] |= (uint8_t)(1u << (start & 7));
        while (sp) {
            uint32_t s = stack[--sp];
            size++;
            if (s < rep) rep = s;
            uint32_t nbr[16]; int k = 0;
            for (int i = 0; i < n; i++) nbr[k++] = s ^ tmask[i];
            nbr[k++] = apply_mask_perm(s, cyc);
            nbr[k++] = apply_mask_perm(s, cyci);
            nbr[k++] = apply_mask_perm(s, swp);
            nbr[k++] = apply_mask_perm(s, tv);
            for (int j = 0; j < k; j++) {
                uint32_t t = nbr[j];
                if (!(visited[t >> 3] & (1u << (t & 7)))) {
                    visited[t >> 3] |= (uint8_t)(1u << (t & 7));
                    if (sp >= stack_cap) { fprintf(stderr, "stack overflow\n"); return 2; }
                    stack[sp++] = t;
                }
            }
        }
        fprintf(out, "%u %llu\n", rep, (unsigned long long)size);
        norbits++; checksum += size;
    }
    fclose(out);
    printf("n=%d: orbits=%llu, checksum=%llu (expected %llu) %s\n",
           n, (unsigned long long)norbits, (unsigned long long)checksum,
           (unsigned long long)total, checksum == total ? "OK" : "FAIL");
    return checksum == total ? 0 : 3;
}
